<?php

/**
 * @file
 * Main file for hooks.
 */
use Drupal\Component\Utility\Html;

/**
 * Implements hook_block_view_alter().
 */
function dummy_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  switch ($build['#id']) {
    # Машинное имя блока.
    case 'linktohelp':
      $build['#attached']['library'][] = 'core/drupal.dialog.ajax';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
//function dummy_preprocess_page(&$variables) {
//  if (\Drupal::service('path.matcher')->isFrontPage()) {
//    $variables['#attached']['library'][] = 'dummy/modal.from.js';
//  }
//}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function dummy_form_contact_message_zakazat_obratnyy_dzvonok_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  # Добавляем элемент куда будем выводить сообщения об ошибках или успешном
  # отправлении формы.
  $form['system_messages'] = [
    '#markup' => '<div id="' . Html::getClass($form_id) . '-messages"></div>',
    '#weight' => -100,
  ];
  # Добавляем наш AJAX колбек для кнопки. Так как он находится в отдельном
  # объекте, то указывать нужно полный путь с пространством имен.
  $form['actions']['submit']['#ajax'] = [
    'callback' => 'Drupal\dummy\AjaxContactSubmit::ajaxSubmitCallback',
    'event' => 'click',
    'progress' => [
      'type' => 'throbber',
    ],
  ];
}

/**
 * @file
 * Main file for hooks and custom functions.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function dummy_preprocess_html(&$variables) {

  $random_message = \Drupal::service('dummy.random_message')->getRandomMessage();
  $msg = \Drupal::messenger();
  $msg->addMessage($random_message);


  $random_drupal_message = \Drupal::service('dummy.random_drupal_message');
  $random_drupal_message->setRandomMessage();

  //$d_form_whis_dependencys = render();
}

/**
 * Implements hook_theme().
 */
function dummy_theme($existing, $type, $theme, $path){
  return [
    'dummy_example_first' => [
      'variables' => [],
    ],
  ];
}

function template_preprocess_dummy_example_first(&$variables){

}
